export interface ReportData {
  title: string;
  content: string;
  date: string;
  author: string;
}

export function generateReportHTML(data: ReportData): string {
  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${data.title}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 20px;
        }
        h1 {
          color: #333;
        }
        .header {
          border-bottom: 1px solid #ccc;
          padding-bottom: 10px;
          margin-bottom: 20px;
        }
        .content {
          line-height: 1.6;
        }
        .footer {
          margin-top: 20px;
          font-size: 0.8em;
          color: #666;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${data.title}</h1>
        <p>Author: ${data.author}</p>
        <p>Date: ${data.date}</p>
      </div>
      <div class="content">
        ${data.content}
      </div>
      <div class="footer">
        Generated by TeachLink
      </div>
    </body>
    </html>
  `;
}
