import { z } from 'zod';
import { COURSE_LIST_CONFIG_SCHEMA_VERSION } from './constants';

export const courseEntrySchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  subtitle: z.string().optional(),
  description: z.string().min(1),
  instructor: z.string().min(1),
  author: z.string().optional(),
  duration: z.string().min(1),
  timeRemaining: z.string().optional(),
  totalLessons: z.number().int().nonnegative(),
  progress: z.number().min(0).max(100),
  category: z.string().min(1),
  size: z.string().optional(),
  thumbnailUrl: z.string().optional(),
  downloaded: z.boolean().default(false),
  featured: z.boolean().default(false),
  tags: z.array(z.string()).default([]),
});

export type CourseEntry = z.infer<typeof courseEntrySchema>;

export const courseListConfigSchema = z.object({
  version: z.literal(COURSE_LIST_CONFIG_SCHEMA_VERSION),
  itemsPerPage: z.number().int().min(1).max(100).default(10),
  sortBy: z.enum(['title', 'progress', 'duration', 'category']).default('title'),
  sortOrder: z.enum(['asc', 'desc']).default('asc'),
  showProgress: z.boolean().default(true),
  showThumbnails: z.boolean().default(true),
  maxFeaturedCourses: z.number().int().min(1).max(20).default(6),
  courses: z.array(courseEntrySchema).default([]),
});

export type CourseListConfig = z.infer<typeof courseListConfigSchema>;

export function createDefaultCourseListConfig(): CourseListConfig {
  return {
    version: COURSE_LIST_CONFIG_SCHEMA_VERSION,
    itemsPerPage: 10,
    sortBy: 'title',
    sortOrder: 'asc',
    showProgress: true,
    showThumbnails: true,
    maxFeaturedCourses: 6,
    courses: [
      {
        id: '1',
        title: 'Web3 UX Design Principles',
        subtitle: 'Create intuitive interfaces for decentralized applications',
        description: 'Create intuitive interfaces for decentralized applications',
        instructor: 'Sarah Johnson',
        author: 'Sarah Johnson',
        duration: '24 hours',
        timeRemaining: '12h remaining',
        totalLessons: 12,
        progress: 68,
        category: 'Design',
        size: '250MB',
        thumbnailUrl:
          'https://thumbs.dreamstime.com/b/matrix-style-digital-rain-green-binary-code-falling-downward-direction-abstract-background-depicting-effect-stream-397887374.jpg',
        downloaded: false,
        featured: true,
        tags: ['web3', 'ux', 'design'],
      },
      {
        id: '2',
        title: 'Smart Contract Security Best Practices',
        subtitle: 'Learn to secure your Cairo smart contracts against vulnerabilities',
        description: 'Learn to secure your Cairo smart contracts against vulnerabilities',
        instructor: 'Michael Chen',
        author: 'Michael Chen',
        duration: '36 hours',
        timeRemaining: '12h remaining',
        totalLessons: 18,
        progress: 45,
        category: 'Security',
        size: '380MB',
        thumbnailUrl:
          'https://static.vecteezy.com/system/resources/previews/053/715/379/non_2x/abstract-green-digital-rain-with-matrix-code-in-futuristic-cyber-background-perfect-for-technology-and-data-themed-visuals-png.png',
        downloaded: true,
        featured: true,
        tags: ['security', 'cairo', 'smart-contracts'],
      },
      {
        id: '3',
        title: 'Scaling DAPps on Starknet',
        subtitle: 'Techniques for building scalable decentralized applications',
        description: 'Techniques for building scalable decentralized applications',
        instructor: 'Alex Rivera',
        author: 'Alex Rivera',
        duration: '48 hours',
        timeRemaining: '12h remaining',
        totalLessons: 24,
        progress: 12,
        category: 'Engineering',
        size: '520MB',
        thumbnailUrl:
          'https://thumbs.dreamstime.com/b/futuristic-laptop-glowing-digital-waves-emerging-screen-dark-setting-399809314.jpg',
        downloaded: false,
        featured: true,
        tags: ['dapps', 'starknet', 'scaling'],
      },
      {
        id: '4',
        title: 'Advanced React Patterns',
        subtitle: 'Master advanced React patterns including render props, HOCs, and hooks',
        description: 'Master advanced React patterns including render props, HOCs, and hooks',
        instructor: 'Sarah Johnson',
        author: 'Sarah Johnson',
        duration: '8 hours',
        totalLessons: 16,
        progress: 0,
        category: 'Web Development',
        size: '180MB',
        thumbnailUrl: 'https://via.placeholder.com/300x200/3B82F6/ffffff?text=React',
        downloaded: false,
        featured: false,
        tags: ['react', 'patterns', 'frontend'],
      },
      {
        id: '5',
        title: 'Machine Learning Fundamentals',
        subtitle: 'Introduction to machine learning algorithms and their applications',
        description: 'Introduction to machine learning algorithms and their applications',
        instructor: 'Dr. Michael Chen',
        author: 'Dr. Michael Chen',
        duration: '12 hours',
        totalLessons: 24,
        progress: 0,
        category: 'Data Science',
        size: '450MB',
        thumbnailUrl: 'https://via.placeholder.com/300x200/10B981/ffffff?text=ML',
        downloaded: false,
        featured: false,
        tags: ['machine-learning', 'data-science', 'ai'],
      },
      {
        id: '6',
        title: 'UI/UX Design Principles',
        subtitle: 'Learn the fundamentals of user interface and user experience design',
        description: 'Learn the fundamentals of user interface and user experience design',
        instructor: 'Emma Davis',
        author: 'Emma Davis',
        duration: '6 hours',
        totalLessons: 12,
        progress: 0,
        category: 'Design',
        size: '120MB',
        thumbnailUrl: 'https://via.placeholder.com/300x200/8B5CF6/ffffff?text=Design',
        downloaded: false,
        featured: false,
        tags: ['design', 'ui', 'ux'],
      },
    ],
  };
}
