/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst, CacheFirst } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST || []);

// Offline fallback page
const offlineFallbackPage = '/offline.html';

// Set up App Shell-style routing
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(({ request, url }: { request: Request; url: URL }) => {
  if (request.mode !== 'navigate') return false;
  if (url.pathname.startsWith('/_')) return false;
  if (url.pathname.match(fileExtensionRegexp)) return false;
  return true;
}, createHandlerBoundToURL('/index.html'));

// Navigation fallback for offline
registerRoute(
  ({ request, url }: { request: Request; url: URL }) => {
    if (request.mode !== 'navigate') return false;
    return true;
  },
  async () => {
    try {
      const response = await fetch(offlineFallbackPage);
      if (response) {
        const cache = await caches.open('offline-fallback');
        await cache.put(offlineFallbackPage, response.clone());
        return response;
      }
    } catch (error) {
      const cache = await caches.open('offline-fallback');
      const cachedResponse = await cache.match(offlineFallbackPage);
      if (cachedResponse) return cachedResponse;
    }
    return new Response('Offline', { status: 503, statusText: 'Service Unavailable' });
  },
);

// Runtime caching for static assets
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.js'),
  new StaleWhileRevalidate({ cacheName: 'static-js' }),
);

registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.css'),
  new StaleWhileRevalidate({ cacheName: 'static-css' }),
);

// Runtime caching for images
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
  new CacheFirst({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  }),
);

registerRoute(
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.match(/\.(jpg|jpeg|svg|gif|webp)$/),
  new CacheFirst({
    cacheName: 'images-ext',
    plugins: [new ExpirationPlugin({ maxEntries: 100 })],
  }),
);

// External images
registerRoute(
  ({ url }) =>
    url.hostname === 'images.unsplash.com' ||
    url.hostname === 'thumbs.dreamstime.com' ||
    url.hostname === 'static.vecteezy.com',
  new StaleWhileRevalidate({
    cacheName: 'external-images',
    plugins: [new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 30 * 24 * 60 * 60 })],
  }),
);

// API requests with NetworkFirst
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-responses',
    plugins: [new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 24 * 60 * 60 })],
  }),
);

// Font caching
registerRoute(
  ({ url }) => url.pathname.match(/\.(woff2?|ttf|otf|eot)$/),
  new CacheFirst({
    cacheName: 'fonts',
    plugins: [new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 365 * 24 * 60 * 60 })],
  }),
);

// Background Sync for offline actions
const bgSyncPlugin = new BackgroundSyncPlugin('teachLinkSyncQueue', {
  maxRetentionTime: 24 * 60,
});

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/sync/'),
  new NetworkFirst({ plugins: [bgSyncPlugin] }),
  'POST',
);

// Handle sync events for background sync
self.addEventListener('sync', (event: SyncEvent) => {
  if (event.tag === 'teachLinkSyncQueue') {
    event.waitUntil(
      // Sync logic handled by the queue
      Promise.resolve(),
    );
  }
});

// Skip waiting and claim clients
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
