/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { REALTIME_OFFLINE_EVENT } from '@/constants/app.constants';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst, CacheFirst, NetworkOnly } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { isObsoleteCacheName, versionedCacheName } from '@/utils/swCacheVersion';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST || []);

// Offline fallback page
const offlineFallbackPage = '/offline.html';

// Set up App Shell-style routing
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(({ request, url }: { request: Request; url: URL }) => {
  if (request.mode !== 'navigate') return false;
  if (url.pathname.startsWith('/_')) return false;
  if (url.pathname.match(fileExtensionRegexp)) return false;
  return true;
}, createHandlerBoundToURL('/index.html'));

// Navigation fallback for offline
registerRoute(
  ({ request }: { request: Request }) => request.mode === 'navigate',
  async () => {
    try {
      const response = await fetch(offlineFallbackPage);
      if (response) {
        const cache = await caches.open(versionedCacheName('offline-fallback'));
        await cache.put(offlineFallbackPage, response.clone());
        return response;
      }
    } catch {
      const cache = await caches.open(versionedCacheName('offline-fallback'));
      const cachedResponse = await cache.match(offlineFallbackPage);
      if (cachedResponse) return cachedResponse;
    }
    return new Response('Offline', { status: 503, statusText: 'Service Unavailable' });
  },
);

// Runtime caching for static assets
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.js'),
  new StaleWhileRevalidate({
    cacheName: versionedCacheName('static-js'),
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
    ],
  }),
);

registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.css'),
  new StaleWhileRevalidate({
    cacheName: versionedCacheName('static-css'),
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
    ],
  }),
);

// Runtime caching for images
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
  new CacheFirst({
    cacheName: versionedCacheName('images'),
    plugins: [new ExpirationPlugin({ maxEntries: 50 })],
  }),
);

registerRoute(
  ({ url }) =>
    url.origin === self.location.origin && url.pathname.match(/\.(jpg|jpeg|svg|gif|webp)$/),
  new CacheFirst({
    cacheName: versionedCacheName('images-ext'),
    plugins: [new ExpirationPlugin({ maxEntries: 100 })],
  }),
);

// External images
registerRoute(
  ({ url }) =>
    url.hostname === 'images.unsplash.com' ||
    url.hostname === 'thumbs.dreamstime.com' ||
    url.hostname === 'static.vecteezy.com',
  new StaleWhileRevalidate({
    cacheName: versionedCacheName('external-images'),
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
    ],
  }),
);

// ─────────────────────────────────────────────────────────────────────────────
// Background Sync for offline mutations
// Must be registered BEFORE the generic /api/ NetworkFirst route below so that
// mutations are routed through the BackgroundSyncPlugin, which queues failed
// requests in IndexedDB and replays them automatically when the sync event fires.
// ─────────────────────────────────────────────────────────────────────────────
const bgSyncPlugin = new BackgroundSyncPlugin('teachLinkSyncQueue', {
  maxRetentionTime: 24 * 60, // 24 hours in minutes
});

// Drains the deterministic offline queue (IndexedDB `teachlink-offline`) when
// connectivity returns. The client listens for OFFLINE_SYNC_REQUESTED and runs
// its transactional, cursor-based drain.
async function notifyClientsToDrain(): Promise<void> {
  const clients = await self.clients.matchAll({
    type: 'window',
    includeUncontrolled: true,
  });
  for (const client of clients) {
    client.postMessage({ type: 'OFFLINE_SYNC_REQUESTED' });
  }
}

self.addEventListener('sync', (event) => {
  if (event.tag === 'teachlink-offline-sync') {
    event.waitUntil(notifyClientsToDrain());
  }
});

// Lesson progress – PATCH /api/lessons/[id]/progress
registerRoute(
  ({ url }) => url.pathname.match(/^\/api\/lessons\/[\w-]+\/progress$/),
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'PATCH',
);

// Notes – POST /api/notes
registerRoute(
  ({ url }) => url.pathname === '/api/notes',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'POST',
);

// Notes – PATCH /api/notes
registerRoute(
  ({ url }) => url.pathname === '/api/notes',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'PATCH',
);

// Notes – DELETE /api/notes
registerRoute(
  ({ url }) => url.pathname === '/api/notes',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'DELETE',
);

// Bookmarks – POST /api/bookmarks
registerRoute(
  ({ url }) => url.pathname === '/api/bookmarks',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'POST',
);

// Bookmarks – PATCH /api/bookmarks
registerRoute(
  ({ url }) => url.pathname === '/api/bookmarks',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'PATCH',
);

// Bookmarks – DELETE /api/bookmarks
registerRoute(
  ({ url }) => url.pathname === '/api/bookmarks',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'DELETE',
);

// User progress – POST /api/user/progress
registerRoute(
  ({ url }) => url.pathname === '/api/user/progress',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'POST',
);

// Quiz results – POST /api/quiz-results
registerRoute(
  ({ url }) => url.pathname === '/api/quiz-results',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'POST',
);

// Course progress – POST /api/course-progress
registerRoute(
  ({ url }) => url.pathname === '/api/course-progress',
  new NetworkOnly({ plugins: [bgSyncPlugin] }),
  'POST',
);

// ─────────────────────────────────────────────────────────────────────────────
// Generic API cache (read requests that don't need background sync)
// ─────────────────────────────────────────────────────────────────────────────
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: versionedCacheName('api-responses'),
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60,
      }),
    ],
  }),
);

// Font caching
registerRoute(
  ({ url }) => url.pathname.match(/\.(woff2?|ttf|otf|eot)$/),
  new CacheFirst({
    cacheName: versionedCacheName('fonts'),
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60,
      }),
    ],
  }),
);

// Skip waiting and claim clients
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }

  // Realtime transports degraded to offline mode (max reconnect attempts exceeded) —
  // broadcast to every open client so the app can switch to offline mode.
  if (event.data && event.data.type === REALTIME_OFFLINE_EVENT) {
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      clients.forEach((client) => client.postMessage({ type: REALTIME_OFFLINE_EVENT }));
    });
  }
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => isObsoleteCacheName(key))
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => {
        clientsClaim();
      }),
  );
});
